name: Update submodules

on:
  workflow_dispatch:
  push:
    branches:
      - $default-branch
  schedule:
    - cron: '30 8,15 * * *'

jobs:
  show_old_submodules:
    name: Update submodules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - run: |
          git fetch
          git submodule update --remote
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: sync submodules
          title: Sync Submodules
          body: Sync Submodules
          branch: sync/submodules
          assignees: RESPONSIBLE_EMPLOYEE_NICKNAME