name: Landing

on:
  workflow_call:
    secrets:
      token:
        required: true


jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project (this repo)
        uses: actions/checkout@v2
        with:
          path: project
      - name: Checkout landing
        uses: actions/checkout@v2
        with:
          repository: RTUITLab/Landing-Front
          path: landing
      - name: Checkout static files
        uses: actions/checkout@v2
        with:
          repository: RTUITLab/Files
          path: files
          lfs: true
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.9
      - name: Parse LANDING.md
        run: |
          python -m pip install -U pip
          pip install -r landing/parser/requirements.txt
          python landing/parser/main.py -s project -t files/content/landing_src/projects_data -r ${{ github.repository }} -b ${{ github.event.repository.default_branch }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          path: files
          token: ${{ secrets.PAT }}
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          commit-message: update information about ${{ github.repository }}
          title: Update information about ${{ github.repository }}
          branch: 'sync/${{ github.repository }}'
          delete-branch: true
          assignees: |
            CAPCHIK
            IvLaptev
          reviewers: |
            CAPCHIK
            IvLaptev
